ALTER TABLE Customer AUTO_INCREMENT = 10001;
ALTER TABLE Media AUTO_INCREMENT = 1000001;
ALTER TABLE Reservation AUTO_INCREMENT = 100001;
ALTER TABLE Author AUTO_INCREMENT = 1;
ALTER TABLE Speaker AUTO_INCREMENT = 1;
ALTER TABLE Actor AUTO_INCREMENT = 1;

